fix

diff --git a/sapbtp-operator-charts/templates/pre-delete-job.yml b/sapbtp-operator-charts/templates/pre-delete-job.yml
--- a/sapbtp-operator-charts/templates/pre-delete-job.yml
+++ b/sapbtp-operator-charts/templates/pre-delete-job.yml
@@ -22,14 +22,39 @@ spec:
           args:
             - "-c"
             - |
-              serviceinstances=$(kubectl get serviceinstances.services.cloud.sap.com -A)
-              servicebindings=$(kubectl get servicebindings.services.cloud.sap.com -A)
+              bindingsoutput=$(kubectl get servicebindings.services.cloud.sap.com -A -o=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace | awk 'NR>1 {print $1,$2}')
+              counter=1
+              for line in $bindingsoutput; do
+                if [ $((counter % 2)) -eq 1 ]; then
+                  name="$line"
+                else
+                  namespace="$line"
+                  echo "Deleting binding with Name: $name, and Namespace: $namespace"
+                  timeout 30 kubectl delete servicebindings.services.cloud.sap.com $name -n $namespace
+                   if [ $? -eq 124 ]; then
+                    echo "Failed to deleted service binding $name"
+                    exit 1
+                  fi
+                fi
+                counter=$((counter + 1))
+              done
 
-              echo "deleting the following service bindings: $servicebindings"
-              kubectl delete servicebindings.services.cloud.sap.com --all --all-namespaces
-
-              echo "deleting the following service instances: $serviceinstances"
-              kubectl delete serviceinstances.services.cloud.sap.com --all --all-namespaces
+              instancesoutput=$(kubectl get serviceinstances.services.cloud.sap.com -A -o=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace | awk 'NR>1 {print $1,$2}')
+              counter=1
+              for line in $instancesoutput; do
+                if [ $((counter % 2)) -eq 1 ]; then
+                  name="$line"
+                else
+                  namespace="$line"
+                  echo "Deleting instance with Name: $name, and Namespace: $namespace"
+                  timeout 30 kubectl delete serviceinstances.services.cloud.sap.com $name -n $namespace
+                  if [ $? -eq 124 ]; then
+                    echo "Failed to deleted service instance $name"
+                    exit 1
+                  fi
+                fi
+                counter=$((counter + 1))
+              done
 
               echo "All service instances and bindings got deleted"
       restartPolicy: Never
